platform :ios, '9.0'
react_native_path = '../node_modules/react-native'

target 'sleepTracker' do

  # Pods for sleepTracker
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
    'RCTAnimation', 
    'RCTImage', 
  ]

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

   # Third party deps podspec link
   pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
   pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
   pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
end
